import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-pink-100 py-4"> {/* Light pink background */}
          <div className="flex space-x-4 items-center pt-2 px-4">
            <Image
              className="rounded-full"
              src="/loguitoconCaro.png"
              alt="Next.js logo"
              width={180}
              height={38}
              priority
            />
            
            <Link href="/" className="text-blue-500 hover:underline">Home</Link>
            <Link href="/page1" className="text-pink-500 hover:underline">Pag1</Link>
            <Link href="/page2" className="text-green-500 hover:underline">Pag2</Link>
          </div>
        </header>
        
        {children}
      </body>
    </html>
  );
}
